deploy:
  stage: deploy
  image: docker:cli
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  variables:
    GIT_STRATEGY: none
  script:
    - cd /var/www/ooci
    - git pull "$CI_REPOSITORY_URL" "$CI_COMMIT_BRANCH"
    - docker compose up -d --build
    - docker image prune -f
